"""init borrowers, activity_entries, lending_settings

Revision ID: 8d6fa7a11c42
Revises: 
Create Date: 2026-04-30 12:17:04.983984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8d6fa7a11c42'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrowers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_username', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('principal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('rate_snapshot', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('days_elapsed', sa.Integer(), nullable=False),
    sa.Column('than_nakulha', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAID', 'OVERDUE', name='borrower_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borrowers_owner_username'), 'borrowers', ['owner_username'], unique=False)
    op.create_table('lending_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_username', sa.String(length=64), nullable=False),
    sa.Column('total_capital', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cash_on_hand', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('daily_rate', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_username', name='uq_lending_settings_owner')
    )
    op.create_index(op.f('ix_lending_settings_owner_username'), 'lending_settings', ['owner_username'], unique=False)
    op.create_table('activity_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borrower_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.Enum('LOAN_RELEASED', 'PAYMENT_RECEIVED', 'PARTIAL_PAYMENT', 'ADDITIONAL_LOAN', 'MISSED_COLLECTION', name='activity_type'), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('payment_method', sa.Enum('CASH', 'GCASH', 'BANK_TRANSFER', name='payment_method'), nullable=True),
    sa.Column('destination', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrowers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_entries_borrower_id'), 'activity_entries', ['borrower_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_entries_borrower_id'), table_name='activity_entries')
    op.drop_table('activity_entries')
    op.drop_index(op.f('ix_lending_settings_owner_username'), table_name='lending_settings')
    op.drop_table('lending_settings')
    op.drop_index(op.f('ix_borrowers_owner_username'), table_name='borrowers')
    op.drop_table('borrowers')
    # ### end Alembic commands ###
